name: Build

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '19.x'
        env:
          TOKEN: ${{ secrets.TOKEN }}
      - name: echo
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          echo "TOKEN:" $TOKEN
      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.TOKEN }}
      - name: Build
        run: npm run prod --if-present
        env:
          NODE_AUTH_TOKEN: ${{ secrets.TOKEN }}
