name: Set merchant identifier

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  set-merchant-id:
    runs-on: nodejs

    env:
      CI: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: echo
        env:
          MERCHANT_IDENTIFIER: ${{ secrets.MERCHANT_IDENTIFIER }}
        run: |
          echo "MERCHANT_IDENTIFIER:" $MERCHANT_IDENTIFIER