name: Set merchant identifier
run-name: Set merchant identifier
on:
  push:
    branches:
      - main

jobs:
  set-merchant-id:
    runs-on: ubuntu-latest
    env:
      CI: true

    steps:
      - uses: actions/checkout@v3
        with:
          node-version: '14'
      env:
          MERCHANT_IDENTIFIER: ${{ secrets.MERCHANT_IDENTIFIER }}

      - name: echo
        run: |
          echo "MERCHANT_IDENTIFIER:" $MERCHANT_IDENTIFIER